<?php
// Landing pages target distinct commercial intents, each with its own problem framing, features,
// use cases and FAQs, so none of them is a thin doorway copy of another.
return [
    [
        'title' => 'Web Hosting in India for Growing Businesses',
        'slug' => 'web-hosting-india',
        'primary_keyword' => 'web hosting india',
        'service' => 'web-hosting',
        'meta_title' => 'Web Hosting in India for Growing Businesses',
        'meta_description' => 'Business web hosting in India with Linux and Windows plans, SSL, domain email and an upgrade path to VPS as your website grows.',
        'hero_subtitle' => 'Get your business website online on managed Linux or Windows hosting, with email on your domain and room to grow.',
        'problem' => "Many Indian small businesses still rely on a free website builder or an old hosting account nobody remembers the login for. Pages load slowly, there is no HTTPS, email addresses are on free providers, and nobody knows whether a backup exists. Every one of these makes the business look less trustworthy to a first-time visitor.",
        'solution' => "SYSCOM web hosting gives you a managed server environment, a control panel to run your site and mailboxes, and support for SSL certificates so every page loads over HTTPS. When your site grows you can move to WordPress-optimised hosting, a VPS or a dedicated server without changing your domain.",
        'features' => "Linux and Windows plans: cPanel for PHP/MySQL and WordPress sites, Plesk for ASP.NET applications\nEmail on your domain: create mailboxes such as sales@ and support@ from the same control panel\nSSL support: run every page on HTTPS and remove browser warnings\nOne-click installers: set up WordPress and other common applications in minutes\nData-centre choice: host close to your customers for faster page loads",
        'benefits' => "A professional web presence that you control\nFaster, more secure pages for visitors\nOne place to manage website, email and domain\nA clear upgrade path instead of a painful migration later",
        'use_cases' => "Local service businesses: a fast site with contact forms, maps and service pages that bring in enquiries\nProfessionals and consultants: a credible portfolio or practice website with a domain email address\nSmall online stores: a WooCommerce or similar store that can move to a VPS as orders increase",
        'content' => "## Getting started\n\n1. Choose or transfer your domain name\n2. Pick a Linux or Windows plan based on how your site is built\n3. Install your website or migrate your existing files and database\n4. Enable SSL and create your business mailboxes\n\nNot sure which plan fits? Our guide on [how to choose web hosting](/blog/how-to-choose-web-hosting-india) walks through the decision.",
        'cta_text' => 'Get hosting advice',
        'faqs' => [
            ['Which hosting plan should a small business start with?', 'Most small business websites start well on a Linux shared hosting plan. If the site is built on WordPress, WordPress-optimised hosting is a good alternative.'],
            ['Can you move my existing website?', 'Yes. The site files, database and email can be migrated to your new hosting account, then DNS is switched once everything has been checked.'],
            ['Do I get email with web hosting?', 'Hosting plans include email accounts on your domain. For larger teams, dedicated business email plans such as Titan or Google Workspace are also available.'],
        ],
    ],
    [
        'title' => 'WordPress Hosting in India, Tuned for Speed',
        'slug' => 'wordpress-hosting-india',
        'primary_keyword' => 'wordpress hosting india',
        'service' => 'wordpress-hosting',
        'meta_title' => 'WordPress Hosting in India, Tuned for Speed',
        'meta_description' => 'Optimised WordPress hosting for Indian businesses and agencies: one-click install, caching, SSL and a server setup built around WordPress.',
        'hero_subtitle' => 'Hosting configured around WordPress, so your pages load faster and your dashboard stays responsive.',
        'problem' => "A WordPress site on a generic hosting setup often feels sluggish: the admin dashboard is slow, pages take seconds to appear, and plugins time out during updates. Slow pages frustrate visitors and make it harder for your content to perform.",
        'solution' => "Optimised WordPress hosting configures the web server, PHP and caching specifically for WordPress. Combined with good site practices such as a lightweight theme, fewer plugins and compressed images, it gives your content a fast, stable home.",
        'features' => "One-click WordPress: install a fresh site in minutes with secure defaults\nWordPress-aware caching: serve repeat page views faster\nPHP configured for WordPress: sensible memory and execution limits for plugins and page builders\nSSL for secure logins: protect wp-admin and customer forms with HTTPS\nSecurity add-ons: optional malware scanning and automated backups",
        'benefits' => "Faster pages and a smoother editing experience\nLess time spent fixing server settings\nA secure base for WooCommerce and membership sites\nRoom to scale to a VPS for high-traffic sites",
        'use_cases' => "Content-led businesses: publish articles and guides that attract organic search traffic\nAgencies: host and maintain several client WordPress sites on a consistent setup\nWooCommerce stores: run a catalogue and checkout on a setup built for WordPress",
        'content' => "## Keep your WordPress site healthy\n\n- Update WordPress core, themes and plugins regularly\n- Remove plugins you no longer use\n- Keep automatic off-site backups\n- Use strong passwords and limit administrator accounts\n\nRead our [website backup plan](/blog/website-backup-strategy-small-business) for a simple routine.",
        'cta_text' => 'Talk to a WordPress specialist',
        'faqs' => [
            ['What is the difference between WordPress hosting and regular hosting?', 'WordPress hosting uses a server configuration, caching and defaults chosen specifically for WordPress, while regular shared hosting is set up for many kinds of applications.'],
            ['Can I host WooCommerce on WordPress hosting?', 'Yes. Small and medium WooCommerce stores run well on optimised WordPress hosting. Large catalogues with heavy traffic may need a VPS.'],
        ],
    ],
    [
        'title' => 'Business Email Hosting on Your Own Domain',
        'slug' => 'business-email-hosting-india',
        'primary_keyword' => 'business email hosting india',
        'service' => 'business-email',
        'meta_title' => 'Business Email Hosting in India on Your Domain',
        'meta_description' => 'Professional email on your company domain with Business Email, Titan or Google Workspace: better trust, admin control and deliverability.',
        'hero_subtitle' => 'Move your team from free email accounts to professional addresses on your own domain.',
        'problem' => "When a business uses free email accounts, customers see addresses that are easy to imitate, messages are more likely to be filtered as spam, and the company loses access to important conversations when an employee leaves.",
        'solution' => "Business email hosting puts every mailbox on your company domain under central administration. Add SPF, DKIM and DMARC records to improve deliverability, and choose the plan that matches how your team works, from simple mailboxes to Google Workspace.",
        'features' => "Mailboxes on your domain: name@yourcompany.in for every team member\nMultiple plan options: Business Email, Titan, Google Workspace and enterprise email\nWebmail and mobile access: read and send mail on any device\nSpam and virus filtering: keep inboxes clean and safer\nCentral administration: add, remove and reset users from one place",
        'benefits' => "Customers instantly recognise and trust your emails\nThe business keeps ownership of every mailbox\nBetter inbox placement with proper DNS authentication\nConsistent branding across every message you send",
        'use_cases' => "Growing teams: give each new hire a company address on day one\nSales and support desks: shared aliases like sales@ and support@ routed to the right people\nCompanies replacing free accounts: migrate existing mail to professional mailboxes",
        'content' => "## Moving from free email\n\n1. Choose a plan and create mailboxes for your team\n2. Point your domain's MX records to the new email service\n3. Add SPF, DKIM and DMARC records\n4. Import old mail if you need the history\n\nCompare options in [business email vs free email](/blog/business-email-vs-free-email).",
        'cta_text' => 'Set up business email',
        'faqs' => [
            ['Can I use business email with my existing domain?', 'Yes. You keep your domain and point its MX records to the email service. Your website can stay where it is.'],
            ['Which is better: Titan or Google Workspace?', 'Titan focuses on email with a modern app at a lower cost; Google Workspace adds Docs, Drive, Meet and other collaboration tools. Choose based on how your team works.'],
        ],
    ],
];
