<?php
/**
 * Regenerates database/seed.sql from the seed/*.php arrays (for phpMyAdmin imports).
 *
 *   php database/build-seed-sql.php
 */
if (PHP_SAPI !== 'cli') {
    http_response_code(404);
    exit;
}

require __DIR__ . '/seeder.php';

function sql_literal($value): string
{
    if ($value === null) {
        return 'NULL';
    }
    if (is_int($value)) {
        return (string) $value;
    }
    return "'" . strtr((string) $value, ["\\" => "\\\\", "'" => "\\'", "\0" => "\\0", "\n" => "\\n", "\r" => "\\r", "\x1a" => "\\Z"]) . "'";
}

$out = "-- SYSCOM GrowthHub demo data. Generated by database/build-seed-sql.php - do not edit by hand.\n"
    . "-- Import AFTER schema.sql. Demo admin: " . DEMO_ADMIN_EMAIL . ' / ' . DEMO_ADMIN_PASSWORD . " (change it!)\n"
    . "-- Dates are relative to when this file was generated.\n\n"
    . "USE syscom_growthhub;\nSET NAMES utf8mb4;\nSTART TRANSACTION;\n\n";

$last = null;
foreach (seed_rows() as [$table, $row]) {
    if ($table !== $last) {
        $out .= "\n-- {$table}\n";
        $last = $table;
    }
    $out .= sprintf("INSERT INTO %s (%s) VALUES (%s);\n", $table, implode(', ', array_keys($row)), implode(', ', array_map('sql_literal', $row)));
}
$out .= "\nCOMMIT;\n";

file_put_contents(__DIR__ . '/seed.sql', $out);
echo 'Wrote database/seed.sql (' . number_format(strlen($out)) . " bytes)\n";
